site_name: ZoneNSI
site_url: https://www.zonensi.fr/
site_author : Bug_Jack_Barron
nav:
    - 'Home' : 'index.md'
    - 'Mathématiques' :
        - 'Seconde' : 
            - 'Présentation' : 'Maths/Seconde/home.md'
            - 'Ensembles de nombres et intervalles' : 
                - 'Ensembles de nombres ' : 'Maths/Seconde/C01/C01_01_Ensembles_Nombres.md'
                - 'Intervalles' : 'Maths/Seconde/C01/C01_02_Intervalles.md'
            - 'Notion de fonctions' : 
                - 'Vocabulaire et rappels' : 'Maths/Seconde/C03/C03_01_Generalite_fonctions.md'
            - 'Algorithmique et bases de Python' :
                - 'Algorithmes, affectations et types de variables' : 'Maths/Seconde/AlgoBases/AffectationTypes.md'
                - 'Programmation en Python et utilisation de Thonny' : 'Maths/Seconde/AlgoBases/ProgrammationPythonThonny.md'
        - 'Première' : 'Maths/Premiere/home.md'
        - 'Terminale' : 'Maths/Terminale/home.md'
    - 'SNT' : 
        - 'Le Web' :
            - 'HTML' : 'WorkInProgress.md'
            - 'CSS' : 'SNT/Web/CSS.md'    
        - 'Données Structurées' :
            - 'Arborescence des fichiers et dossiers ' : 'SNT/Donnees/Arborescence.md'
        - 'Reseaux Informatiques' :
            - 'Adresses IP et TCP/IP' : 'SNT/Reseaux/TCP_IP.md'
            - 'Création de réseaux' : 'SNT/Reseaux/Creation_reseaux.md'
         
    - 'NSI' :
        - 'Première' :
            - 'Bases de Python' : 
                - 'Variables et affectations' : 'WorkInProgress.md'
                - 'Boucles et conditions' : 'WorkInProgress.md'
                - 'Fonctions, assertions et tests unitaires' : 'WorkInProgress.md'
                - 'Projet : Jeu du Pendu' : 'NSI/Premiere/C01/ProjetPendu.md'
            - 'Le codage des données' :
                - 'Binaire et codage des entiers' : 'NSI/Premiere/C02/BinaireCodageEntiers.md'
                - 'Entiers relatifs et flottants' : 'NSI/Premiere/C02/Entiers_relatifs_Flottants.md'
            - 'Le web' :
                - 'HTML strict' : 'NSI/Premiere/C03/HTML.md'
                - 'CSS' : 'NSI/Premiere/C03/CSS.md'
                - 'Introduction à Javascript' : 'NSI/Premiere/C03/JS01.md'
                - 'Javascript, le DOM et les formulaires' : 'NSI/Premiere/C03/JS02.md'
            - 'Les séquences' :
                - 'Tuples et algorithmes de parcours' : 'NSI/Premiere/C04/Tuples.md'
                - 'Listes et compréhensions' : 'NSI/Premiere/C04/Listes_Comprehension.md'
                - 'Premiers algorithmes de tris' : 'NSI/Premiere/C04/Algorithmes_Tri.md'
            
        - 'Terminale' : 
            - 'Présentation' : 'NSI/Terminale/home.md'
            - 'Modularité et POO' :
                - 'Introduction' : 'NSI/Terminale/C01/Intro.md'
                - 'Modules, interfaces, encapsulation' : 'NSI/Terminale/C01/Modularite.md'
                - 'Exceptions' : 'NSI/Terminale/C01/Exceptions.md'
                - 'Introduction à la POO' : 'NSI/Terminale/C01/IntroPOO.md'
            - 'Récursivité' :
                - 'Notion de récursivité' : 'NSI/Terminale/C02/Recursivite.md'
                - 'Applications : Fractales' : 'NSI/Terminale/C02/RecursiviteFractales.md'
                - 'Applications : Tris' : 'NSI/Terminale/C02/RecursiviteTris.md'
                
            - 'Listes, Piles, Files' : 
                - 'Listes chainées' :  'NSI/Terminale/C03/ListesChainees.md'
                - 'Piles et files' : 'NSI/Terminale/C03/Piles_et_files.md'
                - 'TP : Tours de Hanoï' : 'NSI/Terminale/C03/ToursHanoi.md'
                
            - 'Bases de Données et SQL' :
                - 'Modèle relationnel' : 'NSI/Terminale/C04/ModeleRelationnel.md'
                - 'Bases de SQL 1' : 'NSI/Terminale/C04/BasesSQL1.md'
                - 'Bases de SQL 2' : 'NSI/Terminale/C04/BasesSQL2.md'
                - 'Bases de SQL 3' : 'NSI/Terminale/C04/BasesSQL3.md'
                - 'Projet Pokemon' : 'NSI/Terminale/C04/Projet_Pokemon.md'
                
            - 'Arbres Binaires' :
                - 'Définition et propriétés des arbres binaires' : 'NSI/Terminale/C05/Def_Arbres.md'
                - 'Arbres Binaires de Recherche' : 'NSI/Terminale/C05/ABR.md'
                - 'Implémentation des ABR' : 'NSI/Terminale/C05/ABR_Python.md'
                - 'Equilibrage des ABR : les AVL' : 'NSI/Terminale/C05/AVL.md'
                
            - 'Processeurs et Ordonnancement' :
                - 'Les SOCs' : 'NSI/Terminale/C06/Socs.md'
                - 'Gestion des Processus' : 'NSI/Terminale/C06/Processus.md'
                - 'Ordonnancement des processus' : 'NSI/Terminale/C06/Ordonnancement.md'
                - 'Interblocage' : 'NSI/Terminale/C06/Interblocage.md'
           
    - 'Miscellanées' :
        - 'Python' :
            - 'Le langage' : 'WorkInProgress.md'
            - 'Flask' : 'WorkInProgress.md'
            - 'MkDocs' : 'Miscellanees/mkdocs_cmd.md'
            - 'Manim' : 'Miscellanees/Manim/BasesManim.md'
            - 'Pygame' : 
                - 'Installation' : 'Miscellanees/Pygame/InstallationPygame.md'
                - 'Bases de Pygame' : 'Miscellanees/Pygame/Base_pygame.md'
        
plugins : 
    - search
    - macros
    - section-index
    - mkdocs-video
    - page-to-pdf :
        disableOnServe: True
        scale : 0.85
        format : A4
        displayHeaderFooter: True
        pageLoadOptions :
            timeout : 0
                
    
theme:
    name: material
    custom_dir: overrides
    locale: fr
    logo  : assets/icons/house-fill.svg
    features:
        - navigation.instant
        - navigation.top    
        - header.autohide
        - toc.integrate

    palette :
        scheme : slate
        primary : blue grey
        accent : amber
        
extra:
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:admin@zonensi.fr
      name: Écrire à l'auteur
    
  
      
copyright: <a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Licence Creative Commons" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.png" /></a><br />Ce site est mise à disposition selon les termes de la <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Licence Creative Commons Attribution 4.0 International</a>.<br/> 2021 - 2022 - F.Vergniaud
      
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
 
extra_css :
  - extra.css
  

  
markdown_extensions:
  - attr_list
  - pymdownx.highlight
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.smartsymbols
  - pymdownx.critic
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.snippets
  - abbr
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - assets/.icons/
