site_name: ZoneNSI
site_url: https://www.zonensi.fr/
site_author : F. Vergniaud
nav:
    - 'Home' : 'index.md'
    - 'Mathématiques' :
        - 'Seconde' : 
            - 'Présentation' : 'Maths/Seconde/home.md'
            - 'Ensembles de nombres et intervalles' : 
                - 'Ensembles de nombres ' : 'Maths/Seconde/C01/C01_01_Ensembles_Nombres.md'
                - 'Intervalles' : 'Maths/Seconde/C01/C01_02_Intervalles.md'
            - 'Notion de fonctions' : 
                - 'Vocabulaire et rappels' : ''
            - 'Algorithmique et bases de Python' :
                - 'Algorithmes, affectations et types de variables' : 'Maths/Seconde/AlgoBases/AffectationTypes.md'
                - 'Programmation en Python et utilisation de Thonny' : 'Maths/Seconde/AlgoBases/ProgrammationPythonThonny.md'
                - 'Stuctures conditionnelles' : 'Maths/Seconde/AlgoBases/Structures_conditionnelles.md'
                - 'Arithmétique'  : 'Maths/Seconde/AlgoBases/Arithmetique.md'
        - 'Première' : 'Maths/Premiere/home.md'
        - 'Terminale' : 'Maths/Terminale/home.md'
    - 'SNT' : 
        - 'Session Collège' : 'SNT/College/PixelArt.md'
        - 'Le Web' :
            - 'HTML' : 'SNT/Web/Bases_HTML.md'
            - 'CSS' : 'SNT/Web/CSS.md'    
        - 'Données Structurées' :
            - 'Arborescence des fichiers et dossiers ' : 'SNT/Donnees/Arborescence.md'
        - 'Reseaux Informatiques' :
            - 'Adresses IP et TCP/IP' : 'SNT/Reseaux/TCP_IP.md'
            - 'Création de réseaux' : 'SNT/Reseaux/Creation_reseaux.md'
            - 'Pour aller plus loin, DHCP et DNS' : 'SNT/Reseaux/DHCP_DNS.md'
        - 'Images Numériques' :
            - 'Noir, Blanc, Gris' : 'SNT/Images/NB.md'
            - 'La couleur et le RGB' : 'SNT/Images/RGB.md'
        - 'Géolocalisation'  :
            - 'Coordonnées et GPS' : 'SNT/Geolocalisation/geolocalisation.md'
            - 'Recherche du chemin le plus court' : 'SNT/Geolocalisation/Dijkstra.md'
         
    - 'NSI' :
        - 'Première' :
            - 'Bases de Python' : 
                - 'Variables et affectations' : 'NSI/Premiere/C01/Bases_Python_1.md'
                - 'Boucles et conditions' : 'NSI/Premiere/C01/Conditions_Boucles.md'
                - 'Fonctions, assertions et tests unitaires' : 'NSI/Premiere/C01/Fonctions_Assertions.md'
                - 'Projet : Pierre-Feuille-Ciseaux' : 'NSI/Premiere/Projets/PFC/PFC.md'
                - 'Projet : Bandit-Manchot' : 'NSI/Premiere/Projets/BanditManchot/Projet_Bandit_Manchot.md'
                - 'Projet : Jeu du Pendu' : 'NSI/Premiere/Projets/Pendu/ProjetPendu.md'
                
            - 'Le codage des données' :
                - 'Binaire et codage des entiers' : 'NSI/Premiere/C02/BinaireCodageEntiers.md'
                - 'Entiers relatifs et flottants' : 'NSI/Premiere/C02/Entiers_relatifs_Flottants.md'
                - 'Codage des caractères' : 'NSI/Premiere/C02/CodageCaractere.md'
            - 'Le web' :
                - 'HTML strict' : 'NSI/Premiere/C03/HTML.md'
                - 'CSS' : 'NSI/Premiere/C03/CSS.md'
                - 'Introduction à Javascript' : 'NSI/Premiere/C03/JS01.md'
                - 'Javascript, le DOM et les formulaires' : 'NSI/Premiere/C03/JS02.md'
                - 'Projet Jeu Textuel en JS' : 'NSI/Premiere/Projets/DungeonJS/Dungeon.md'
                #- 'Projet Rover Mars' : 'NSI/Premiere/Projets/NasaWeb/Nasa_Web.md'
            - 'Les séquences' :
                - 'Tuples et algorithmes de parcours' : 'NSI/Premiere/C04/Tuples.md'
                - 'Listes et compréhensions' : 'NSI/Premiere/C04/Listes_Comprehension.md'
                - 'Premiers algorithmes de tris' : 'NSI/Premiere/C04/Algorithmes_Tri.md'
                - 'Tableaux à 2 dimensions : Matrices ' : 'NSI/Premiere/C04/Tableaux2D.md'
                - 'Les images Matricielles' : 'NSI/Premiere/C04/ImagesBMP.md'
                - 'Projet : Démineur' : 'NSI/Premiere/Projets/demineurP5/projet_demineur.md'
            - 'Architecture matérielle' :
                - 'Historique' : 'NSI/Premiere/C05/Historique.md'
                - 'Architecture' : 'NSI/Premiere/C05/Architecture.md' 
            - 'Traitement des données en tables' :
                - 'Les dictionnaires' : 'NSI/Premiere/C06/Dictionnaires.md'
                - 'Les fichiers CSV' : 'NSI/Premiere/C06/CSV.md'
            - 'Les algorithmes gloutons' :
                - 'Algorithmes Gloutons' : 'NSI/Premiere/C07/Algorithmes_Gloutons.md'
            - 'Réseaux' :
                - 'Internet : historique' : 'NSI/Premiere/C08/Histoire.md'
                - 'Réseaux, Trames, Paquets' : 'NSI/Premiere/C08/Trames.md'
                - 'Transmission Client-Serveur' : 'NSI/Premiere/C08/Client_Serveur.md'
                
                
        - 'Terminale' : 
            - 'Présentation' : 'NSI/Terminale/home.md'
            - 'Modularité et POO' :
                - 'Introduction' : 'NSI/Terminale/C01/Intro.md'
                - 'Modules, interfaces, encapsulation' : 'NSI/Terminale/C01/Modularite.md'
                - 'Exceptions' : 'NSI/Terminale/C01/Exceptions.md'
                - 'Introduction à la POO' : 'NSI/Terminale/C01/IntroPOO.md'
                - 'Projet : ClickerWars' : 'NSI/Terminale/Projets/ClickersWars/CW.md'
            - 'Récursivité' :
                - 'Notion de récursivité' : 'NSI/Terminale/C02/Recursivite.md'
                - 'Applications : Fractales' : 'NSI/Terminale/C02/RecursiviteFractales.md'
                - 'Applications : Tris' : 'NSI/Terminale/C02/RecursiviteTris.md'
                
            - 'Listes, Piles, Files' : 
                - 'Listes chainées' :  'NSI/Terminale/C03/ListesChainees.md'
                - 'Piles et files' : 'NSI/Terminale/C03/Piles_et_files.md'
                - 'TP : Tours de Hanoï' : 'NSI/Terminale/C03/ToursHanoi.md'
                
            - 'Bases de Données et SQL' :
                - 'Modèle relationnel' : 'NSI/Terminale/C04/ModeleRelationnel.md'
                - 'Bases de SQL 1' : 'NSI/Terminale/C04/BasesSQL1.md'
                - 'Bases de SQL 2' : 'NSI/Terminale/C04/BasesSQL2.md'
                - 'Bases de SQL 3' : 'NSI/Terminale/C04/BasesSQL3.md'
                - 'Projet Pokemon' : 'NSI/Terminale/C04/Projet_Pokemon.md'
                
            - 'Arbres Binaires' :
                - 'Définition et propriétés des arbres binaires' : 'NSI/Terminale/C05/Def_Arbres.md'
                - 'Arbres Binaires de Recherche' : 'NSI/Terminale/C05/ABR.md'
                - 'Implémentation des ABR' : 'NSI/Terminale/C05/ABR_Python.md'
                - 'Equilibrage des ABR : les AVL' : 'NSI/Terminale/C05/AVL.md'
                
            - 'Processeurs et Ordonnancement' :
                #- 'Les SOCs' : 'NSI/Terminale/C06/Socs.md'
                - "Système d'exploitation Linux" : 'NSI/Terminale/C06/Linux.md'
                - 'Gestion des Processus' : 'NSI/Terminale/C06/Processus.md'
                - 'Ordonnancement des processus' : 'NSI/Terminale/C06/Ordonnancement.md'
                - 'Interblocage' : 'NSI/Terminale/C06/Interblocage.md'
            
            - 'Réseaux' :
                - 'Notion de routage' : 'NSI/Terminale/C07/Routage.md'
                - 'Protocoles RIP' : 'NSI/Terminale/C07/RIP.md'
                - 'Protocole OSPF' : 'NSI/Terminale/C07/OSPF.md'
                
            - 'Programmation dynamique' :
                - 'Principes et exemples' : 'NSI/Terminale/C08/ProgDyn.md'
                - 'Alignements de séquences' : 'NSI/Terminale/C08/alignSeq.md'
                
            - 'Graphes et parcours' :
                - 'Notion de Graphe' : 'NSI/Terminale/C09/graphe.md'
                - 'Les graphes en Python' : 'NSI/Terminale/C09/graphe_python.md'
                - 'Parcours de Graphes ' : 'NSI/Terminale/C09/parcours.md'
                
            - 'Recherche textuelles' : 'NSI/Terminale/C10/BoyerMoore.md'
            - 'Sécurisation des communications' : 'NSI/Terminale/C11/Securisation.md'
    - 'Enseignement Scientifique' :
        - 'Données et IA' :
            - 'Stockage des données' : 'ES/stockage.md'
               
           
    - 'Miscellanées' :
        - 'Python' :
            - 'Le langage' : 
                - 'Manipulation des fichiers textes' : 'Miscellanees/Bases_Python/Fichiers_Textes.md'
            - 'Flask' : 'WorkInProgress.md'
            - 'MkDocs' : 'Miscellanees/mkdocs_cmd.md'
            - 'Manim' : 'Miscellanees/Manim/BasesManim.md'
            - 'Pygame' : 
                - 'Installation' : 'Miscellanees/Pygame/InstallationPygame.md'
                - 'Bases de Pygame' : 'Miscellanees/Pygame/Base_pygame.md'
            - 'P5' :
                - 'P5 et Thonny' : 'Miscellanees/p5_Thonny.md'
                - 'Bases de P5 ' : 'Miscellanees/utilisationP5.md'
        - 'REGEX' : 'Miscellanees/regex.md'
        - 'BDD, SQL et PHP' : 'Miscellanees/Challenge_Ada_Lovelace/BDD.md'
        
        
plugins : 
    - search
    - macros
    - section-index
    - mkdocs-video
    - page-to-pdf :
        disableOnServe: True
        scale : 0.85
        format : A4
        displayHeaderFooter: True
        pageLoadOptions :
            timeout : 0
                
    
theme:
    name: material
    custom_dir: my_theme_customizations/
    locale: fr
    logo  : assets/icons/house-fill.svg
    features:
        - navigation.instant
        - navigation.top
        - navigation.sections
        - header.autohide
        - toc.integrate
        - content.code.copy
        - content.code.select

    palette :
        - scheme : slate
          toggle :
            icon : material/brightness-4
            name : Switch to light mode
          primary : blue grey
          accent : amber
        - scheme : default
          toggle :
            icon : material/brightness-7
            name : Switch to dark mode
          primary : blue grey
          accent : amber
      
            
extra:
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:fabien.vergniaud arobase gmail.com
      name: Écrire à l'auteur
    
  
      
copyright: <a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Licence Creative Commons" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.png" /></a><br />Ce site est mise à disposition selon les termes de la <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Licence Creative Commons Attribution 4.0 International</a>.<br/> 2021 - 2024 - F.Vergniaud
      
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdn.jsdelivr.net/gh/rod2ik/cdn@main/mkdocs/javascripts/mkdocs-graphviz.js
  - xtra/javascripts/interpreter.js



 
extra_css :
  - extra.css
  - xtra/stylesheets/pyoditeur.css

  

  
markdown_extensions:
  - attr_list
  - pymdownx.highlight
  - mkdocs_graphviz :
        light_theme: 000000      # Any HTML Color Name or any HTML Hexadecimal color code WITHOUT the `#` sign
        dark_theme: FFFFFF       # Any HTML Color Name or any HTML Hexadecimal color code WITHOUT the `#` sign
        color: 789ABC            # Any HTML Color Name or any HTML Hexadecimal color code WITHOUT the `#` sign
        bgcolor: none            # Any HTML Color Name or any HTML Hexadecimal color code WITHOUT the `#` sign
        graph_color: 789ABC      # Any HTML Color Name or any HTML Hexadecimal color code WITHOUT the `#` sign
        graph_fontcolor: 789ABC  # Any HTML Color Name or any HTML Hexadecimal color code WITHOUT the `#` sign
        node_color: FF0000       # Any HTML Color Name or any HTML Hexadecimal color code WITHOUT the `#` sign
        node_fontcolor: 0000FF   # Any HTML Color Name or any HTML Hexadecimal color code WITHOUT the `#` sign
        edge_color: 00FF00       # Any HTML Color Name or any HTML Hexadecimal color code WITHOUT the `#` sign
        edge_fontcolor: 789ABC   # Any HTML Color Name or any HTML Hexadecimal color code WITHOUT the `#` sign
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.smartsymbols
  - pymdownx.critic
  - pymdownx.superfences :
        custom_fences :
            -   name : mermaid
                class : mermaid
                format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.keys
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - pymdownx.tabbed :
      alternate_style: true 
  - pymdownx.snippets
  - abbr
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - assets/.icons/

  
