site_name: ZoneNSI
site_url: https://www.zonensi.fr/
site_author : Bug_Jack_Barron
nav:
    - 'Home' : index.md
    - 'Mathématiques' :
        - 'Seconde' : 'Maths\Seconde\home.md'
        - 'Première' : 'Maths\Premiere\home.md'
        - 'Terminale' : 'Maths\Terminale\home.md'
    - 'SNT' : 'snt_home.md'
    - 'NSI' :
        - 'Première' : 'NSI\Premiere\home.md'
        - 'Terminale' : 'NSI\Terminale\home.md'
    - 'Miscellanées' :
        - 'Python' :
            - 'Le langage' 
            - 'Flask' 
            - 'MkDocs' : 'Miscellanees\mkdocs_cmd.md'
            - 'Manim' 

 
plugins : 
    - search
    - macros
    
theme:
    name: material
    locale: fr
    logo  : assets/icons/house-fill.svg
    features:
        - navigation.instant
        - navigation.top    
        - header.autohide
        - toc.integrate

    palette :
        scheme : slate
        primary : blue grey
        accent : amber
        
extra:
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:admin@zonensi.fr
      name: Écrire à l'auteur
      
copyright: <a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Licence Creative Commons" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.png" /></a><br />Ce(tte) œuvre est mise à disposition selon les termes de la <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Licence Creative Commons Attribution 4.0 International</a>.
<br/> 2021 - F.Vergniaud
      
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
 
extra_css :
  - extra.css
  

  
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.smartsymbols
  - pymdownx.critic
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.snippets
  - abbr
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - assets\.icons\